/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import exceptions.RegistroDuplicadoException;
import exceptions.RegistroNoEncontradoException;
import exceptions.ValidacionException;
import model.Estudiante;
import service.GestorMatriculas;

/**
 *
 * @author lajch
 */
public class Principal extends javax.swing.JFrame {

    private final GestorMatriculas gestor;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form Principal
     * @param gestor
     */
    public Principal(GestorMatriculas gestor) {
        initComponents();
        this.gestor = gestor;
        setLocationRelativeTo(null);
        setTitle("Gestión de Matrícula - Persona 3");
        configurarTabla();
        refrescarTabla();
    }

    private void configurarTabla() {

        modeloTabla = new DefaultTableModel(
                new Object[]{"Código", "Estudiante", "Curso", "Créditos", "Estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblMatriculas.setModel(modeloTabla);
    }

    private void refrescarTabla() {

        modeloTabla.setRowCount(0);

        List<Estudiante> lista = gestor.listar();

        for (Estudiante e : lista) {
            modeloTabla.addRow(new Object[]{
                e.getCodigoMatricula(),
                e.getNombreEstudiante(),
                e.getCurso(),
                e.getCreditos(),
                e.getEstado()
            });
        }
    }

    private String obtenerCodigoSeleccionado() {

        int fila = tblMatriculas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar una matrícula de la tabla.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return null;
        }

        return modeloTabla.getValueAt(fila, 0).toString();
    }

    private void buscarEnTabla(String codigo) {

        for (int i = 0; i < modeloTabla.getRowCount(); i++) {

            String codigoTabla = modeloTabla.getValueAt(i, 0).toString();

            if (codigoTabla.equals(codigo)) {
                tblMatriculas.setRowSelectionInterval(i, i);
                tblMatriculas.scrollRectToVisible(tblMatriculas.getCellRect(i, 0, true));
                return;
            }
        }
    }

    private void activarAcciones(boolean activo) {
        mnuRegistrar.setEnabled(activo);
        mnuEditar.setEnabled(activo);
        mnuEliminar.setEnabled(activo);
        mnuBuscar.setEnabled(activo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatriculas = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblInstruccion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        mnuNuevo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        menuMatriculas = new javax.swing.JMenu();
        mnuRegistrar = new javax.swing.JMenuItem();
        mnuEditar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuBuscar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        mnuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de matrículas"));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de Matrícula");

        tblMatriculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Estudiante", "Curso", "Créditos", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMatriculas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblMatriculas);

        btnActualizar.setText("Actualizar tabla");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblInstruccion.setText("Seleccione una fila para editar, eliminar o consultar desde el menú Matrículas.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstruccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuArchivo.setText("Archivo");

        mnuNuevo.setText("Nuevo");
        mnuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(mnuNuevo);
        menuArchivo.add(jSeparator1);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(mnuSalir);

        jMenuBar1.add(menuArchivo);

        menuMatriculas.setText("Matrículas");

        mnuRegistrar.setText("Registrar");
        mnuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarActionPerformed(evt);
            }
        });
        menuMatriculas.add(mnuRegistrar);

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        menuMatriculas.add(mnuEditar);

        mnuEliminar.setText("Eliminar");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        menuMatriculas.add(mnuEliminar);
        menuMatriculas.add(jSeparator2);

        mnuBuscar.setText("Buscar");
        mnuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarActionPerformed(evt);
            }
        });
        menuMatriculas.add(mnuBuscar);

        jMenuBar1.add(menuMatriculas);

        menuAyuda.setText("Ayuda");

        mnuAcerca.setText("Acerca de");
        mnuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaActionPerformed(evt);
            }
        });
        menuAyuda.add(mnuAcerca);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        refrescarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoActionPerformed
        refrescarTabla();
        JOptionPane.showMessageDialog(this,
                "Tabla actualizada correctamente.",
                "Nuevo",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuNuevoActionPerformed

    private void mnuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarActionPerformed
        activarAcciones(false);
        try {
            EstudianteDialog dialog = new EstudianteDialog(this, EstudianteDialog.Mode.CREAR, null);
            dialog.setVisible(true);

            Estudiante nuevo = dialog.getResult();

            if (nuevo != null) {
                try {
                    gestor.crear(nuevo);
                } catch (ValidacionException | RegistroDuplicadoException ex) {
                    JOptionPane.showMessageDialog(this,
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    refrescarTabla();
                }
            }
        } finally {
            activarAcciones(true);
        }
    }//GEN-LAST:event_mnuRegistrarActionPerformed

    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
        String codigo = obtenerCodigoSeleccionado();

        if (codigo != null) {
            activarAcciones(false);
            try {
                Estudiante existente = gestor.buscar(codigo);

                EstudianteDialog dialog = new EstudianteDialog(this, EstudianteDialog.Mode.EDITAR, existente);
                dialog.setVisible(true);

                Estudiante editado = dialog.getResult();

                if (editado != null) {
                    gestor.editar(editado);
                }
            } catch (ValidacionException | RegistroDuplicadoException | RegistroNoEncontradoException ex) {
                JOptionPane.showMessageDialog(this,
                        ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            } finally {
                refrescarTabla();
                activarAcciones(true);
            }
        }
    }//GEN-LAST:event_mnuEditarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        String codigo = obtenerCodigoSeleccionado();

        if (codigo != null) {
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Desea eliminar la matrícula con código " + codigo + "?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                activarAcciones(false);
                try {
                    gestor.eliminar(codigo);
                } catch (ValidacionException | RegistroNoEncontradoException ex) {
                    JOptionPane.showMessageDialog(this,
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    refrescarTabla();
                    activarAcciones(true);
                }
            }
        }
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void mnuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Digite el código de matrícula:");

        if (codigo == null || codigo.trim().isEmpty()) {
            return;
        }

        activarAcciones(false);
        try {
            Estudiante e = gestor.buscar(codigo.trim());

            JOptionPane.showMessageDialog(this,
                    "Matrícula encontrada:\n\n"
                    + "Código: " + e.getCodigoMatricula() + "\n"
                    + "Estudiante: " + e.getNombreEstudiante() + "\n"
                    + "Curso: " + e.getCurso() + "\n"
                    + "Créditos: " + e.getCreditos() + "\n"
                    + "Estado: " + e.getEstado(),
                    "Buscar matrícula",
                    JOptionPane.INFORMATION_MESSAGE);

            buscarEnTabla(e.getCodigoMatricula());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            refrescarTabla();
            activarAcciones(true);
        }
    }//GEN-LAST:event_mnuBuscarActionPerformed

    private void mnuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaActionPerformed
        JOptionPane.showMessageDialog(this,
                "Práctica Programada #3\n"
                + "Gestión de Matrícula\n"
                + "SC-303 Programación Cliente/Servidor Concurrente\n"
                + "Grupo 5\n\n"
                + "Persona 3: Ventana principal, menú y tabla.",
                "Acerca de",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAcercaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblInstruccion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuMatriculas;
    private javax.swing.JMenuItem mnuAcerca;
    private javax.swing.JMenuItem mnuBuscar;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuNuevo;
    private javax.swing.JMenuItem mnuRegistrar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTable tblMatriculas;
    // End of variables declaration//GEN-END:variables
}
